def get_package_name(flavor)
  UI.user_error!("Missing required parameter: variant") if flavor.nil?

  valid_flavors = ["SakshamStag", "SakshamUat", "Saksham", "Xushrukha", "Niramay"]
  UI.user_error!("Invalid variant: #{flavor}") unless valid_flavors.include?(flavor)

  base_package = "org.piramalswasthya.sakhi"

  suffixes = {
    "SakshamStag" => ".saksham.stag",
    "SakshamUat"  => ".saksham.uat",
    "Saksham"     => ".saksham",
    "Xushrukha"   => ".xushrukha",
    "Niramay"     => ".niramay"
  }

  package_name = "#{base_package}#{suffixes[flavor]}"
  UI.message "Using package name: #{package_name}"
  package_name
end


def latest_googleplay_version_code(package_name)
  tracks = ['production', 'beta', 'alpha', 'internal']
  version_codes = []

  tracks.each do |track|
    begin
      version_codes.concat(
        google_play_track_version_codes(
          track: track,
          package_name: package_name
        )
      )
    rescue
      UI.message "No version found for #{track} track"
    end
  end

  version_codes.max || 0
end


default_platform(:android)

platform :android do

  desc "Build and Distribute Debug APK to Firebase"
  lane :build_and_distribute_debug do |options|

    UI.user_error!("variant is required") if options[:variant].nil?
    UI.user_error!("FIREBASE_APP_ID is missing") if ENV['FIREBASE_APP_ID'].to_s.empty?


    new_version_code = options[:version_code]&.to_i || 1
    new_version_name = "#{new_version_code}.0.0"

    UI.message "Building Debug with versionCode=#{new_version_code}, versionName=#{new_version_name}"

    File.open("../version/version.properties", "w") do |file|
      file.puts("VERSION=#{new_version_name}")
      file.puts("VERSIONCODE=#{new_version_code}")
    end

    gradle(
      task: "clean assemble#{options[:variant]}Debug"
    )

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      service_credentials_file: "firebase_credentials.json",
      release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
      groups_file: "FirebaseAppDistributionConfig/groups.txt",
      debug: true
    )
  end


  desc "Build, Sign, and Distribute Release AAB to Play Store"
  lane :build_and_distribute_release do |options|

    UI.user_error!("variant is required") if options[:variant].nil?

    keystore_path = File.expand_path('../keystore.jks')
    package_name = get_package_name(options[:variant])

    new_version_code = latest_googleplay_version_code(package_name) + 1
    new_version_name = "#{new_version_code}.0.0"

    UI.message "Release versionCode=#{new_version_code}, versionName=#{new_version_name}"

    File.open("../version/version.properties", "w") do |file|
      file.puts("VERSION=#{new_version_name}")
      file.puts("VERSIONCODE=#{new_version_code}")
    end

    gradle(
      task: "clean bundle#{options[:variant]}Release",
      properties: {
        "android.injected.signing.store.file" => keystore_path,
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD']
      }
    )

    upload_to_play_store(
      track: "internal",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft",
      version_code: new_version_code,
      package_name: package_name
    )
  end

end
